return {
    'kovetskiy/sxhkd-vim',
    "b0o/schemastore.nvim",
    "cohama/lexima.vim",
    'andymass/vim-matchup',
    "tpope/vim-repeat",
    "tpope/vim-capslock",
    "tpope/vim-eunuch",
    "tpope/vim-sensible",
    "tpope/vim-endwise",
    "tpope/vim-dadbod",
    "kristijanhusak/vim-dadbod-ui",
    "nvim-lua/plenary.nvim",
    "amadeus/vim-convert-color-to",
    "neovim/nvim-lspconfig",
    "norcalli/nvim-colorizer.lua",
    'nvim-tree/nvim-web-devicons',
    "Hoffs/omnisharp-extended-lsp.nvim",
    "nvim-lua/lsp_extensions.nvim",
    "mbbill/undotree",
    "OrangeT/vim-csharp",
    { "nvim-telescope/telescope-fzf-native.nvim", build = "make" },
    "jlcrochet/vim-razor",
    "nathom/filetype.nvim",
    { "ellisonleao/gruvbox.nvim",                 lazy = false },
}
